let groep6Woorden = [
  ['lucht','noch','onzichtbaar','oprichting','rechtstreeks','reusachtig','slachtoffer','techniek','voorlichting','waarachter','wellicht'],
  ['reis','eigenschap','inleiding','neiging','opleiding','terrein','uitbreiding'],
  ['ijs','aanwijzing','ongetwijfeld','uitgeverij','wijziging'],
  ['koning','goedkeuring','hervorming','hulpverlening','medewerking','opvatting','overtuiging','tegenstelling','uitdrukking','uitwerking','voldoening','vordering','vormgeving','waardering','waarneming'],
  ['de','akte','apostel','datgene','degene','ergernis','gave','hoogstens','karakter','naarmate','tevergeefs','weduwe','zodoende'],
  ['bezoek','bediening','behoud','benoeming','beperking','beperkt','beschikbaar'],
  ['getal','gemeenschap','genot','gevangene','gezag','gezelschap'],
  ['verkeer','verandering','verbazing','verbeelding','verbetering','verdeling','vereniging','vergadering','vergelijking','vergunning','vervolgens'],
  ['ontbijt','ontbinding','ontdekking','ontleding','ontspanning','ontwerper','ontwikkeling'],
  ['vrolijk','aanzienlijk','burgerlijk','christelijk','dergelijk','gebruikelijk','geleidelijk','gemeentelijk','herhaaldelijk','lichamelijk','namelijk','noodzakelijk','noordelijk','openlijk','schriftelijk','vermoedelijk','verschrikkelijk','voortreffelijk'],
  ['jarig','gebrekkig','matig','rechtvaardig','regelmatig','toekomstig','volledig','vrijwillig','willekeurig'],
  ['figuur','bibliotheek','bioscoop','centimeter','dirigent','dominee','horizon','kabinet','kandidaat','kapitaal','kardinaal','limonade','linie','minister','officier','origineel','politiek','positief','president'],
  ['snelheid','afwezigheid','bijzonderheid','eenzaamheid','verlegenheid','voorzichtigheid'],
  ['majesteit','activiteit','kwaliteit','majesteit','universiteit],','[thee','althans','katholiek','thans','theater','theorie'],
  ['elektrisch','communistisch','historisch','praktisch','romantisch','technisch','theoretisch'],
  ['directie','actie','directie','reactie','redactie'],
  ['politie','combinatie','definitie','demonstratie','gratie','informatie','justitie','organisatie','publicatie','relatie','traditie'],
  ['cel','centrale','citroen','concert','procent'],
  ['actief','acteur','advocaat','aspect','camera','categorie','circa','collega','competitie','componist','conclusie','contract','cultuur','discussie','insect','inspecteur','lectuur','perfect','plastic','redacteur','respect','secretaris','tactiek'],
  ['café','café','comité','coupé','logé'],
  ['liniaal','liniaal','materiaal','sociaal','speciaal'],
  ['garage','bagage','etage','garage','horloge'],
  ['chauffeur','chef','chirurg','chocola','machine','club','absoluut','abstract','club','eb','objectief','observatie','subsidie'],
  ['hond','achterstand','advies','gemeenteraad','indertijd','kameraad','spannend','tegenstand','voortdurend','wereldoorlog','zogenaamd'],
  ['jager','aantekening','alcohol','basis','begroting','berekening','beschaving','bovenop','drama','energie','enzovoort','evenmin','grotendeels','hagel','historie','integendeel','kolonel','kolonie','merendeel','momenteel','moraal','nagenoeg','overeenkomst','profeet','professor','protestant','republiek','resultaat','rubriek','tevoren','tezamen','voorzover'],
  ['apen','advocaten','bedragen','kandidaten','leraren','minuten','oorzaken'],
  ['profeten','sieraden','sigaren','uitspraken'],
  ['dokter','artistiek','atmosfeer','christen','kwestie','onderdeel','orgaan','pardon','parlement','register','transport','volstrekt'],
  ['fietsen','contacten','inlichtingen','insecten','instrumenten','voorschriften','vorsten'],
  ['bakker','aanpassing','ellendig','herinnering','hoeverre','ingewikkeld','klassiek','koppeling','middelbaar','Middeleeuwen','missie','monnik','onmiddellijk'],
  ['ballen','kanonnen','kennissen','leraressen','ogenblikken','processen','raketten','vonnissen','voorstellen'],
  ['sleutels','conducteurs','etalages','horloges','passagiers','prestaties','provincies','romans','series','studies','tegenstanders','voorstanders','werkgevers','werknemers'],
  ['hoeveelheden','minderheden','omstandigheden','overheden','plechtigheden'],
  ['piano\'s','agenda\'s','collega\'s','diploma\'s','ijsco\'s','pinda\'s','pony\'s','programma\'s','risico\'s','taxi\'s'],
  ['oliën','bacteriën','koloniën','oliën'],
  ['knieën','calorieën','categorieën','drieën','harmonieën','industrieën','knieën','melodieën'],
  ['tweeën','Jeën','ideeën','reeën','tweeën','weeën','zeeën'],
  ['gouden','blikken','diamanten','gouden','houten','ijzeren','katoenen','koperen','stenen'],
  ['bijv.','ca.','enz.','nl.','o.a.'],
  ['Amsterdam','Berlijn','Brussel','Londen','Madrid','Moskou','New York','Parijs','Rome'],
  ['Nederland','Australië','België','Canada','China','Griekenland','Ierland','India','Italië','Japan','Oostenrijk','Portugal','Suriname'],
  ['Nederlander','Amerikaan','Chinees','Duitser','Engelsman','Fransman','Portugees','Spanjaard','Zweed'],
  ['Nederlands(e)','Chinese','Duitse','Europese','Griekse','Italiaanse','Japanse','Noord-Hollandse','Noorse','Russische','Spaanse','Zweedse','Zwitserse']
];

let groep6WerkWoorden = [
  ['kleuren','bellen','belonen','benoemen','bestuderen','betalen','bouwen','breien','dalen','delen','draaien','drogen','dromen','eindigen','fluisteren','gebeuren','gillen','gooien','groeien','halen','huilen','huren','kleuren','leren','leveren','mopperen','oefenen','openen','opvolgen','proberen','regelen','regeren','rekenen','rennen','roeien','ruilen','spelen','trouwen','uitnodigen','vieren','waaien','wonen','zwaaien'],
  ['reizen','blozen','bonzen','glanzen','grazen','niezen','peinzen','prijzen','razen','reizen','verbazen','verhuizen','verwaarlozen','vrezen'],
  ['leven','beleven','beloven','beven','draven','durven','erven','geloven','handhaven','hoeven','leven','proeven','streven','verven','weven','zweven'],
  ['antwoorden','aanbranden','afbeelden','afleiden','antwoorden','beantwoorden','bereiden','besteden','bevrijden','bloeden','braden','branden','broeden','doden','dulden','kleden','laden','landen','luiden','melden','opladen','opvoeden','raden','redden','schaden','schudden','spreiden','uitbroeden','verblinden','verbranden','verkleden','verleiden','vermoorden','verwonden','voeden','wedden','wenden'],
  ['werken','aankloppen','afdekken','bakken','bedanken','beperken','bereiken','boksen','botsen','bukken','danken','dansen','drukken','eisen','fietsen','gapen','gebruiken','glimlachen','haken','hakken','hopen','kloppen','knikken','knippen','knopen','koken','kraken','kussen','lachen','fikken','maken','merken','pakken','plaatsen','pompen','raken','roken','schoppen','slepen','slikken','smeken','snoepen','staken','stoppen','straffen','vereisen','verwerken','vissen','wensen','werken'],
  ['praten','aantasten','aanzetten','afwachten','afzetten','barsten','begroeten','berichten','bezetten','feesten','groeten','haasten','haten','inlichten','kaarten','neerzetten','oogsten','opletten','oprichten','planten','praten','putten','richten','rusten','samenvatten','schatten','sporten','spotten','starten','storten','trachten','twisten','uitrusten','vergroten','verplichten','verrichten','verwachten','vluchten','wachten','zuchten'],
  ['roepen','afbreken','bedriegen','beginnen','breken','buigen','dragen','drinken','duiken','hangen','helpen','kijken','klimmen','klinken','knijpen','kruipen','liegen','liggen','lopen','nemen','ontvangen','roepen','ruiken','slapen','spreken','stelen','trekken','vallen','vangen','varen','verdwijnen','vliegen','wegen','werpen','winnen','zingen', 'zwemmen', 'zwijgen'],
  ['lijden','aanbieden','afsnijden','aftreden','bestrijden','bevinden','bidden','bieden','binden','gebieden','gelden','glijden','lijden','ondervinden','optreden','opwinden','rijden','schelden','snijden','strijden','uitvinden','uitzenden','verbieden','verbinden','vermijden','vinden','worden','zenden','zitten','aansluiten','achterlaten','besluiten','bezitten','bijten','eten','fluiten','genieten','gieten','laten','meten','ontbijten','opmeten','schieten','sluiten','smelten','snuiten','spuiten','vechten','vergeten','verwijten','vlechten','weglaten','zitten'],
  ['kiezen','aanwijzen','afwijzen','bewijzen','blazen','genezen','kiezen','lezen','opblazen','prijzen','uitblazen','uitkiezen','uitwijzen','verkiezen','verwijzen','voorlezen','wijzen'],
  ['geven','aangeven','achterblijven','begraven','blijven','doorgeven','geven','graven','opschrijven','overblijven','schrijven','schuiven','sterven','stuiven','toegeven','verblijven','verschuiven','voorschrijven','werven','wrijven','zwerven'],
  ['zoeken','aankomen','afstaan','afzien','bedenken','bevriezen','bezoeken','brengen','denken','doen','doorbrengen','gaan','hebben','houden','inslaan','komen','kopen','kunnen','meedoen','meegaan','moeten','mogen','nazeggen','opkopen','slaan','staan','uitzien','uitzoeken','verdenken','verkopen','verliezen','verzoeken','voldoen','vriezen','weten','zeggen','zien','zijn','zoeken','zullen']
];

let groep6 = groep6Woorden.concat(groep6WerkWoorden);